
app = "painel-fubanga"

[build]
  image = "python:3.10-slim"

[env]
  MONGO_URI = "mongodb+srv://Fubanga:M27p08_14@clusters.axdjwb8.mongodb.net/?retryWrites=true&w=majority&appName=Clusters"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
